"""Initial

Revision ID: 265f32697186
Revises: 
Create Date: 2020-10-12 20:58:32.608934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '265f32697186'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
